import type { Activity, TrekkingDetail, CalendarEvent } from "./types"

// ─── Activities ──────────────────────────────────────────────────────────────

export const ACTIVITIES: Activity[] = [
  {
    id: "laguna-esmeralda-express",
    title: "Laguna Esmeralda, Visita Express",
    cover_image: "/laguna-esmeralda-emerald-lake-ushuaia-forest-trail.jpg",
    price_from: 45,
    currency: "USD",
    difficulty: "Fácil",
    duration: "4 hs",
    category: "Laguna Esmeralda",
    availability_dates: ["2026-11-08", "2026-11-15", "2026-11-22", "2026-12-06", "2026-12-13"],
    capacity_remaining: 8,
    rating: 4.97,
    reviews_count: 124,
    popular: true,
    location: "Ushuaia",
    calendarioSlug: "laguna-esmeralda-visita-express",
    galleryImages: [
      { src: "/laguna-esmeralda-emerald-lake-ushuaia-forest-trail.jpg", alt: "Laguna Esmeralda - Vista principal" },
      { src: "/laguna-esmeralda-ushuaia-emerald-lake-mountains.jpg", alt: "Montañas alrededor de Laguna Esmeralda" },
      { src: "/placeholder.jpg", alt: "Sendero hacia Laguna Esmeralda" },
      { src: "/placeholder.jpg", alt: "Bosque de Tierra del Fuego" },
      { src: "/placeholder.jpg", alt: "Flora local" },
    ],
  },
  {
    id: "laguna-esmeralda-sunset",
    title: "Laguna Esmeralda Sunset",
    cover_image: "/laguna-esmeralda-ushuaia-emerald-lake-mountains.jpg",
    price_from: 55,
    currency: "USD",
    difficulty: "Fácil",
    duration: "5 hs",
    category: "Trekking",
    availability_dates: ["2026-11-09", "2026-11-16", "2026-11-23", "2026-12-07"],
    capacity_remaining: 6,
    rating: 4.94,
    reviews_count: 87,
    popular: true,
    location: "Ushuaia",
    calendarioSlug: "laguna-esmeralda-sunset",
    galleryImages: [
      { src: "/laguna-esmeralda-ushuaia-emerald-lake-mountains.jpg", alt: "Atardecer en Laguna Esmeralda" },
      { src: "/placeholder.jpg", alt: "Vista al atardecer" },
      { src: "/placeholder.jpg", alt: "Reflejo en la laguna" },
      { src: "/placeholder.jpg", alt: "Montañas al atardecer" },
    ],
  },
  {
    id: "glaciar-vinciguerra",
    title: "Glaciar Vinciguerra y Laguna de los Témpanos",
    cover_image: "/vinciguerra-glacier-ushuaia-iceberg-lagoon.jpg",
    price_from: 75,
    currency: "USD",
    difficulty: "Moderado",
    duration: "8 hs",
    category: "Trekking",
    availability_dates: ["2026-11-12", "2026-11-19", "2026-12-03", "2026-12-10"],
    capacity_remaining: 10,
    rating: 4.91,
    reviews_count: 63,
    location: "Ushuaia",
    calendarioSlug: "glaciar-vinciguerra",
    galleryImages: [
      { src: "/vinciguerra-glacier-ushuaia-iceberg-lagoon.jpg", alt: "Glaciar Vinciguerra" },
      { src: "/placeholder.jpg", alt: "Laguna de los Témpanos" },
      { src: "/placeholder.jpg", alt: "Témpanos de hielo" },
      { src: "/placeholder.jpg", alt: "Vista del glaciar" },
      { src: "/placeholder.jpg", alt: "Paisaje glaciar" },
    ],
  },
  {
    id: "ojo-del-albino",
    title: "Ojo del Albino — Ice Trekking",
    cover_image: "/ojo-del-albino-glacier-ushuaia-mountain-peaks.jpg",
    price_from: 95,
    currency: "USD",
    difficulty: "Avanzado",
    duration: "9 hs",
    category: "Trekking",
    availability_dates: ["2026-11-14", "2026-11-28", "2026-12-05", "2026-12-19"],
    capacity_remaining: 4,
    rating: 4.99,
    reviews_count: 42,
    popular: true,
    location: "Ushuaia",
    calendarioSlug: "ojo-del-albino",
    galleryImages: [
      { src: "/ojo-del-albino-glacier-ushuaia-mountain-peaks.jpg", alt: "Glaciar Ojo del Albino" },
      { src: "/placeholder.jpg", alt: "Cumbre de montaña" },
      { src: "/placeholder.jpg", alt: "Vista panorámica" },
      { src: "/placeholder.jpg", alt: "Hielo y nieve" },
      { src: "/placeholder.jpg", alt: "Paisaje de alta montaña" },
    ],
  },
  {
    id: "campamento-vinciguerra",
    title: "Campamento Vinciguerra — Noche en la montaña",
    cover_image: "/patagonia-sunset-campfire-hikers-silhouette-mounta.jpg",
    price_from: 140,
    currency: "USD",
    difficulty: "Avanzado",
    duration: "2 días",
    category: "Trekking",
    availability_dates: ["2026-11-21", "2026-12-12", "2027-01-09"],
    capacity_remaining: 6,
    rating: 5.0,
    reviews_count: 18,
    popular: true,
    location: "Ushuaia",
    calendarioSlug: "campamento-vinciguerra",
    galleryImages: [
      { src: "/patagonia-sunset-campfire-hikers-silhouette-mounta.jpg", alt: "Atardecer en campamento" },
      { src: "/placeholder.jpg", alt: "Fogata en la montaña" },
      { src: "/placeholder.jpg", alt: "Estrellas australes" },
      { src: "/placeholder.jpg", alt: "Campamento nocturno" },
      { src: "/placeholder.jpg", alt: "Vista matinal" },
    ],
  },
  {
    id: "parque-nacional-tierra-del-fuego",
    title: "Parque Nacional Tierra del Fuego",
    cover_image: "/tierra-mayor-valley-ushuaia-peatlands-mountains.jpg",
    price_from: 35,
    currency: "USD",
    difficulty: "Fácil",
    duration: "3 hs",
    category: "Parque Nacional",
    availability_dates: ["2026-11-07", "2026-11-10", "2026-11-14", "2026-11-17", "2026-11-21"],
    capacity_remaining: 15,
    rating: 4.85,
    reviews_count: 210,
    location: "Ushuaia",
    galleryImages: [
      { src: "/tierra-mayor-valley-ushuaia-peatlands-mountains.jpg", alt: "Valle Tierra Mayor" },
      { src: "/placeholder.jpg", alt: "Turberas de Tierra del Fuego" },
      { src: "/placeholder.jpg", alt: "Senderos del parque" },
      { src: "/placeholder.jpg", alt: "Flora local" },
    ],
  },
  {
    id: "canal-beagle-navegacion",
    title: "Navegación por el Canal Beagle",
    cover_image: "/lago-argentino-patagonia-crystal-blue-water.jpg",
    price_from: 60,
    currency: "USD",
    difficulty: "Fácil",
    duration: "3.5 hs",
    category: "Navegación / Canal Beagle",
    availability_dates: ["2026-11-08", "2026-11-11", "2026-11-15", "2026-11-18", "2026-11-22"],
    capacity_remaining: 20,
    rating: 4.88,
    reviews_count: 176,
    popular: true,
    location: "Ushuaia",
    galleryImages: [
      { src: "/lago-argentino-patagonia-crystal-blue-water.jpg", alt: "Canal Beagle" },
      { src: "/placeholder.jpg", alt: "Navegación en canal" },
      { src: "/placeholder.jpg", alt: "Fauna marina" },
      { src: "/placeholder.jpg", alt: "Islas del canal" },
      { src: "/placeholder.jpg", alt: "Vistas del Beagle" },
    ],
  },
  {
    id: "city-tour-ushuaia",
    title: "City Tour Ushuaia — La ciudad del fin del mundo",
    cover_image: "/group-trekking-mountain-hiking-ushuaia-patagonia.jpg",
    price_from: 25,
    currency: "USD",
    difficulty: "Fácil",
    duration: "2.5 hs",
    category: "City tour",
    availability_dates: ["2026-11-08", "2026-11-09", "2026-11-10", "2026-11-15", "2026-11-16"],
    capacity_remaining: 25,
    rating: 4.78,
    reviews_count: 295,
    location: "Ushuaia",
    galleryImages: [
      { src: "/group-trekking-mountain-hiking-ushuaia-patagonia.jpg", alt: "Vistas de Ushuaia" },
      { src: "/placeholder.jpg", alt: "Centro de la ciudad" },
      { src: "/placeholder.jpg", alt: "Monumento del fin del mundo" },
      { src: "/placeholder.jpg", alt: "Puerto de Ushuaia" },
    ],
  },
]

// ─── Trekking details ────────────────────────────────────────────────────────

export const TREKKING_DETAILS: Record<string, TrekkingDetail> = {
  "susana-pm": {
    title: "Susana PM",
    location: "Tierra del Fuego",
    difficulty: "Moderado",
    image: "/ushuaia-martial-glacier-mountain-view.jpg",
    duration: "1 día",
    groupSize: "8-12",
    price: "$180.000",
    type: "Trekking",
    description: "Trekking vespertino por los senderos más pintorescos de Tierra del Fuego, ideal para disfrutar de las mejores vistas al atardecer.",
    longDescription: "La Susana PM es una experiencia única que te permite explorar la naturaleza fueguina durante la tarde, cuando la luz crea un ambiente mágico. Este trekking moderado te llevará por senderos bien marcados con vistas panorámicas del canal Beagle y las montañas circundantes.",
    itinerary: [{ day: "Tarde", title: "Trekking Vespertino", description: "Recogida 14:00. Traslado al inicio del sendero. Trekking de 4 horas por paisajes patagónicos. Merienda en mirador. Retorno a Ushuaia al anochecer." }],
    included: ["Guía profesional", "Transporte desde/hasta Ushuaia", "Merienda y bebidas calientes", "Seguro de excursión"],
    notIncluded: ["Equipamiento personal", "Almuerzo", "Propinas"],
    requirements: ["Edad mínima: 10 años", "Nivel de fitness: Moderado", "No se requiere experiencia previa"],
    dates: ["15 Nov 2025", "22 Nov 2025", "29 Nov 2025", "6 Dic 2025"],
  },
  "ojo-albino-pernocte": {
    title: "Ojo del Albino con Pernocte",
    location: "Tierra del Fuego",
    difficulty: "Avanzado",
    image: "/ushuaia-martial-glacier-mountain-view.jpg",
    duration: "2 días",
    groupSize: "6-10",
    price: "$395.000",
    type: "Campamento",
    description: "Expedición con campamento nocturno en uno de los lugares más remotos y hermosos de Tierra del Fuego.",
    longDescription: "Una aventura de dos días que combina trekking de alta montaña con la experiencia única de acampar bajo las estrellas australes. El Ojo del Albino es una laguna glaciar de difícil acceso que recompensa con vistas incomparables.",
    itinerary: [
      { day: "Día 1", title: "Ascenso y Campamento", description: "Salida 8:00am. Trekking de 6-7 horas hasta el campamento base. Instalación de carpas. Cena caliente. Observación de estrellas." },
      { day: "Día 2", title: "Exploración y Descenso", description: "Desayuno. Exploración del Ojo del Albino. Almuerzo. Descenso de 4-5 horas. Regreso a Ushuaia por la tarde." },
    ],
    included: ["Guía de montaña certificado", "Equipo de camping completo", "Todas las comidas", "Transporte", "Seguro de trekking"],
    notIncluded: ["Equipamiento personal (botas, ropa de abrigo)", "Sleeping bag personal", "Snacks extras"],
    requirements: ["Edad mínima: 16 años", "Nivel de fitness: Avanzado", "Experiencia previa en trekking", "Buena condición física"],
    dates: ["20 Nov 2025", "4 Dic 2025", "18 Dic 2025"],
  },
  "laguna-esmeralda-express": {
    title: "Laguna Esmeralda, Visita Express",
    location: "Tierra del Fuego",
    difficulty: "Fácil",
    image: "/laguna-esmeralda-emerald-lake-ushuaia-forest-trail.jpg",
    duration: "1 día",
    groupSize: "8-15",
    price: "$165.000",
    type: "Trekking",
    description: "La forma más rápida y eficiente de conocer la famosa Laguna Esmeralda, ideal para viajeros con poco tiempo.",
    longDescription: "Esta versión express del clásico trekking a Laguna Esmeralda está diseñada para maximizar tu tiempo. En medio día conocerás uno de los lugares más emblemáticos de Tierra del Fuego sin sacrificar la calidad de la experiencia.",
    itinerary: [{ day: "Mañana", title: "Visita Express", description: "Salida 8:00am. Traslado (30 min). Trekking directo a la laguna (2.5 horas). Tiempo en la laguna (30 min). Retorno rápido (2 horas). Regreso a Ushuaia 14:00." }],
    included: ["Guía profesional", "Transporte", "Snacks y bebidas", "Seguro"],
    notIncluded: ["Almuerzo completo", "Equipamiento personal"],
    requirements: ["Edad mínima: 8 años", "Nivel de fitness: Básico", "Apto para principiantes"],
    dates: ["10 Nov 2025", "17 Nov 2025", "24 Nov 2025", "1 Dic 2025", "8 Dic 2025"],
  },
  "laguna-esmeralda-sunset": {
    title: "Laguna Esmeralda Sunset",
    location: "Tierra del Fuego",
    difficulty: "Fácil",
    image: "/laguna-esmeralda-emerald-lake-ushuaia-forest-trail.jpg",
    duration: "1 día",
    groupSize: "8-12",
    price: "$195.000",
    type: "Trekking",
    description: "Experiencia mágica para presenciar el atardecer en la laguna con los colores más espectaculares del día.",
    longDescription: "La Laguna Esmeralda cobra una dimensión completamente diferente durante el atardecer. Los colores del cielo patagónico se reflejan en las aguas turquesas creando un espectáculo natural inolvidable. Esta excursión vespertina incluye cena junto a la laguna.",
    itinerary: [{ day: "Tarde/Noche", title: "Trekking al Atardecer", description: "Salida 15:00. Trekking pausado de 3 horas. Llegada antes del atardecer. Cena caliente junto a la laguna. Observación del sunset. Retorno con linternas frontales. Llegada 22:00." }],
    included: ["Guía profesional", "Transporte", "Cena caliente completa", "Linternas frontales", "Seguro"],
    notIncluded: ["Equipamiento personal", "Bebidas alcohólicas"],
    requirements: ["Edad mínima: 10 años", "Nivel de fitness: Básico", "Cómodo caminando en penumbras"],
    dates: ["12 Nov 2025", "19 Nov 2025", "26 Nov 2025", "3 Dic 2025"],
  },
  "torres-rio-chico": {
    title: "Torres del Rio Chico, el TOUR de las Lagunas",
    location: "Tierra del Fuego",
    difficulty: "Avanzado",
    image: "/ushuaia-martial-glacier-mountain-view.jpg",
    duration: "3 días",
    groupSize: "6-10",
    price: "$470.000",
    type: "Campamento",
    description: "La expedición más completa de Tierra del Fuego, recorriendo múltiples lagunas y torres de montaña.",
    longDescription: "Esta es la expedición definitiva para aventureros experimentados. Durante tres días explorarás los rincones más remotos y salvajes de Tierra del Fuego, visitando lagunas escondidas, torres de roca y glaciares con dos noches de campamento en alta montaña.",
    itinerary: [
      { day: "Día 1", title: "Inicio de la Expedición", description: "Salida temprano. Trekking de 7 horas hasta primer campamento. Cruce de ríos y bosques. Instalación de campamento. Cena." },
      { day: "Día 2", title: "Tour de Lagunas", description: "Día completo explorando lagunas glaciares. Ascenso a miradores. Almuerzo de montaña. Segunda noche en campamento alto." },
      { day: "Día 3", title: "Torres y Descenso", description: "Visita a las Torres del Río Chico. Descenso de 6 horas. Almuerzo en ruta. Regreso a Ushuaia al atardecer." },
    ],
    included: ["Guía experto en alta montaña", "Equipo completo de camping", "Todas las comidas", "Transporte", "Seguro especializado"],
    notIncluded: ["Equipamiento personal técnico", "Sleeping bag personal", "Snacks personales"],
    requirements: ["Edad mínima: 18 años", "Nivel de fitness: Avanzado/Experto", "Experiencia previa obligatoria en trekking de múltiples días", "Certificado médico requerido"],
    dates: ["25 Nov 2025", "9 Dic 2025", "6 Ene 2026"],
  },
  "ojo-albino-ice-trekking": {
    title: "Ojo del Albino. Ice Trekking",
    location: "Tierra del Fuego",
    difficulty: "Avanzado",
    image: "/ushuaia-martial-glacier-mountain-view.jpg",
    duration: "1 día",
    groupSize: "6-8",
    price: "$250.000",
    type: "Montañismo",
    description: "Trekking técnico sobre hielo con crampones y equipo de montañismo en el glaciar Ojo del Albino.",
    longDescription: "Una experiencia de montañismo para aventureros que quieren llevar su trekking al siguiente nivel. Caminarás sobre hielo milenario usando crampones y equipo técnico, explorando grietas glaciares y formaciones de hielo bajo la supervisión de guías certificados en alta montaña.",
    itinerary: [{ day: "Día Completo", title: "Ice Trekking Técnico", description: "Salida 7:00am. Aproximación al glaciar (3 horas). Colocación de equipo técnico. Ice trekking de 4 horas sobre hielo. Almuerzo en el glaciar. Descenso (2.5 horas). Retorno 18:00." }],
    included: ["Guía de alta montaña AAGM", "Equipo técnico completo (crampones, arnés, casco)", "Transporte", "Almuerzo de montaña", "Seguro especializado"],
    notIncluded: ["Botas de montaña (se pueden alquilar)", "Ropa técnica personal", "Snacks extras"],
    requirements: ["Edad mínima: 16 años", "Nivel de fitness: Avanzado", "Experiencia previa en trekking", "Sin vértigo", "Certificado médico recomendado"],
    dates: ["18 Nov 2025", "2 Dic 2025", "16 Dic 2025", "30 Dic 2025"],
  },
  "laguna-esmeralda-confort": {
    title: "Laguna Esmeralda, Confort y Aventura",
    location: "Tierra del Fuego",
    difficulty: "Fácil",
    image: "/laguna-esmeralda-emerald-lake-ushuaia-forest-trail.jpg",
    duration: "1 día",
    groupSize: "8-12",
    price: "$190.000",
    type: "Trekking",
    description: "La experiencia premium de Laguna Esmeralda con servicios adicionales, almuerzo gourmet y grupo reducido.",
    longDescription: "Para quienes buscan combinar aventura con comodidad, esta versión premium del trekking a Laguna Esmeralda incluye un ritmo más pausado, almuerzo gourmet preparado por chef, bebidas premium, grupo reducido y atención personalizada. La forma más cómoda de vivir esta experiencia.",
    itinerary: [{ day: "Día Completo", title: "Experiencia Premium", description: "Recogida 9:00am. Traslado privado. Trekking pausado (3.5 horas) con paradas fotográficas. Almuerzo gourmet junto a la laguna. Tiempo libre. Retorno tranquilo (2.5 horas). Llegada 17:00." }],
    included: ["Guía bilingüe especializado", "Transporte privado", "Almuerzo gourmet y bebidas premium", "Kit de trekking (bastones, mochila pequeña)", "Seguro premium"],
    notIncluded: ["Equipamiento personal", "Propinas"],
    requirements: ["Edad mínima: 8 años", "Nivel de fitness: Básico", "Ideal para familias", "Apto para todas las edades"],
    dates: ["14 Nov 2025", "21 Nov 2025", "28 Nov 2025", "5 Dic 2025", "12 Dic 2025"],
  },
  "glaciar-vinciguerra": {
    title: "Glaciar Vinciguerra y Laguna de los Témpanos",
    location: "Tierra del Fuego",
    difficulty: "Moderado",
    image: "/ushuaia-martial-glacier-mountain-view.jpg",
    duration: "1 día",
    groupSize: "8-12",
    price: "$200.000",
    type: "Trekking",
    description: "Ascenso al glaciar Vinciguerra con vistas panorámicas de 360° y la impresionante Laguna de los Témpanos.",
    longDescription: "Este trekking te llevará a uno de los miradores más espectaculares de Tierra del Fuego. El ascenso al Glaciar Vinciguerra recompensa con vistas de 360 grados del Canal Beagle, las montañas circundantes y la increíble Laguna de los Témpanos con sus icebergs flotantes.",
    itinerary: [{ day: "Día Completo", title: "Ascenso al Glaciar", description: "Salida 8:00am. Traslado (30 min). Ascenso progresivo de 5 horas a través de bosque andino y zona alpina. Almuerzo con vista al glaciar y la laguna. Tiempo para explorar y fotografiar. Descenso (3 horas). Retorno 18:00." }],
    included: ["Guía profesional", "Transporte desde/hasta Ushuaia", "Almuerzo tipo box lunch mejorado", "Bebidas calientes", "Bastones de trekking", "Seguro de excursión"],
    notIncluded: ["Equipamiento personal (botas, mochila, ropa de abrigo)", "Snacks adicionales", "Propinas"],
    requirements: ["Edad mínima: 12 años", "Nivel de fitness: Moderado", "Experiencia básica en trekking recomendada", "Buena condición física"],
    dates: ["16 Nov 2025", "23 Nov 2025", "30 Nov 2025", "7 Dic 2025", "14 Dic 2025", "21 Dic 2025"],
  },
}

// ─── Calendar events ─────────────────────────────────────────────────────────

export const CALENDAR_EVENTS: CalendarEvent[] = [
  // Noviembre 2026
  { id: "laguna-esmeralda", title: "Laguna Esmeralda", date: "2026-11-07", month: "Noviembre", year: 2026, difficulty: "Fácil", location: "Ushuaia, Tierra del Fuego", duration: "1 día", groupSize: "2-8", price: "$35.000", spotsLeft: 6 },
  { id: "glaciar-martial", title: "Glaciar Martial", date: "2026-11-08", month: "Noviembre", year: 2026, difficulty: "Fácil", location: "Ushuaia, Tierra del Fuego", duration: "Medio día", groupSize: "2-8", price: "$15.000", spotsLeft: 8 },
  { id: "laguna-esmeralda", title: "Laguna Esmeralda", date: "2026-11-14", month: "Noviembre", year: 2026, difficulty: "Fácil", location: "Ushuaia, Tierra del Fuego", duration: "1 día", groupSize: "2-8", price: "$35.000", spotsLeft: 5 },
  { id: "ojo-del-albino", title: "Glaciar Ojo del Albino", date: "2026-11-15", month: "Noviembre", year: 2026, difficulty: "Moderado", location: "Ushuaia, Tierra del Fuego", duration: "1 día", groupSize: "2-6", price: "$45.000", spotsLeft: 4 },
  { id: "vinciguerra", title: "Glaciar Vinciguerra y Laguna Azul", date: "2026-11-21", month: "Noviembre", year: 2026, difficulty: "Avanzado", location: "Ushuaia, Tierra del Fuego", duration: "1 día", groupSize: "2-6", price: "$65.000", spotsLeft: 3 },
  { id: "laguna-esmeralda", title: "Laguna Esmeralda", date: "2026-11-22", month: "Noviembre", year: 2026, difficulty: "Fácil", location: "Ushuaia, Tierra del Fuego", duration: "1 día", groupSize: "2-8", price: "$35.000", spotsLeft: 8 },
  { id: "glaciar-martial", title: "Glaciar Martial", date: "2026-11-23", month: "Noviembre", year: 2026, difficulty: "Fácil", location: "Ushuaia, Tierra del Fuego", duration: "Medio día", groupSize: "2-8", price: "$15.000", spotsLeft: 7 },
  { id: "ojo-del-albino", title: "Glaciar Ojo del Albino", date: "2026-11-28", month: "Noviembre", year: 2026, difficulty: "Moderado", location: "Ushuaia, Tierra del Fuego", duration: "1 día", groupSize: "2-6", price: "$45.000", spotsLeft: 5 },
  { id: "laguna-esmeralda", title: "Laguna Esmeralda", date: "2026-11-29", month: "Noviembre", year: 2026, difficulty: "Fácil", location: "Ushuaia, Tierra del Fuego", duration: "1 día", groupSize: "2-8", price: "$35.000", spotsLeft: 2 },
  // Diciembre 2026
  { id: "laguna-esmeralda", title: "Laguna Esmeralda", date: "2026-12-05", month: "Diciembre", year: 2026, difficulty: "Fácil", location: "Ushuaia, Tierra del Fuego", duration: "1 día", groupSize: "2-8", price: "$35.000", spotsLeft: 8 },
  { id: "glaciar-martial", title: "Glaciar Martial", date: "2026-12-06", month: "Diciembre", year: 2026, difficulty: "Fácil", location: "Ushuaia, Tierra del Fuego", duration: "Medio día", groupSize: "2-8", price: "$15.000", spotsLeft: 6 },
  { id: "ojo-del-albino", title: "Glaciar Ojo del Albino", date: "2026-12-07", month: "Diciembre", year: 2026, difficulty: "Moderado", location: "Ushuaia, Tierra del Fuego", duration: "1 día", groupSize: "2-6", price: "$45.000", spotsLeft: 4 },
  { id: "vinciguerra", title: "Glaciar Vinciguerra y Laguna Azul", date: "2026-12-12", month: "Diciembre", year: 2026, difficulty: "Avanzado", location: "Ushuaia, Tierra del Fuego", duration: "1 día", groupSize: "2-6", price: "$65.000", spotsLeft: 3 },
  { id: "laguna-esmeralda", title: "Laguna Esmeralda", date: "2026-12-13", month: "Diciembre", year: 2026, difficulty: "Fácil", location: "Ushuaia, Tierra del Fuego", duration: "1 día", groupSize: "2-8", price: "$35.000", spotsLeft: 10 },
  { id: "campamento-vinciguerra", title: "Campamento Vinciguerra", date: "2026-12-14", month: "Diciembre", year: 2026, difficulty: "Avanzado", location: "Ushuaia, Tierra del Fuego", duration: "2 días", groupSize: "2-6", price: "$130.000", spotsLeft: 4 },
  { id: "glaciar-martial", title: "Glaciar Martial", date: "2026-12-19", month: "Diciembre", year: 2026, difficulty: "Fácil", location: "Ushuaia, Tierra del Fuego", duration: "Medio día", groupSize: "2-8", price: "$15.000", spotsLeft: 8 },
  { id: "laguna-esmeralda", title: "Laguna Esmeralda", date: "2026-12-20", month: "Diciembre", year: 2026, difficulty: "Fácil", location: "Ushuaia, Tierra del Fuego", duration: "1 día", groupSize: "2-8", price: "$35.000", spotsLeft: 5 },
  { id: "ojo-del-albino", title: "Glaciar Ojo del Albino", date: "2026-12-21", month: "Diciembre", year: 2026, difficulty: "Moderado", location: "Ushuaia, Tierra del Fuego", duration: "1 día", groupSize: "2-6", price: "$45.000", spotsLeft: 3 },
  { id: "laguna-esmeralda", title: "Laguna Esmeralda", date: "2026-12-27", month: "Diciembre", year: 2026, difficulty: "Fácil", location: "Ushuaia, Tierra del Fuego", duration: "1 día", groupSize: "2-8", price: "$35.000", spotsLeft: 12 },
  { id: "vinciguerra", title: "Glaciar Vinciguerra y Laguna Azul", date: "2026-12-28", month: "Diciembre", year: 2026, difficulty: "Avanzado", location: "Ushuaia, Tierra del Fuego", duration: "1 día", groupSize: "2-6", price: "$65.000", spotsLeft: 2 },
  // Enero 2027
  { id: "laguna-esmeralda", title: "Laguna Esmeralda", date: "2027-01-03", month: "Enero", year: 2027, difficulty: "Fácil", location: "Ushuaia, Tierra del Fuego", duration: "1 día", groupSize: "2-8", price: "$35.000", spotsLeft: 8 },
  { id: "glaciar-martial", title: "Glaciar Martial", date: "2027-01-04", month: "Enero", year: 2027, difficulty: "Fácil", location: "Ushuaia, Tierra del Fuego", duration: "Medio día", groupSize: "2-8", price: "$15.000", spotsLeft: 7 },
  { id: "ojo-del-albino", title: "Glaciar Ojo del Albino", date: "2027-01-10", month: "Enero", year: 2027, difficulty: "Moderado", location: "Ushuaia, Tierra del Fuego", duration: "1 día", groupSize: "2-6", price: "$45.000", spotsLeft: 5 },
  { id: "vinciguerra", title: "Glaciar Vinciguerra y Laguna Azul", date: "2027-01-11", month: "Enero", year: 2027, difficulty: "Avanzado", location: "Ushuaia, Tierra del Fuego", duration: "1 día", groupSize: "2-6", price: "$65.000", spotsLeft: 4 },
  { id: "laguna-esmeralda", title: "Laguna Esmeralda", date: "2027-01-17", month: "Enero", year: 2027, difficulty: "Fácil", location: "Ushuaia, Tierra del Fuego", duration: "1 día", groupSize: "2-8", price: "$35.000", spotsLeft: 6 },
  { id: "campamento-vinciguerra", title: "Campamento Vinciguerra", date: "2027-01-18", month: "Enero", year: 2027, difficulty: "Avanzado", location: "Ushuaia, Tierra del Fuego", duration: "2 días", groupSize: "2-6", price: "$130.000", spotsLeft: 3 },
  { id: "glaciar-martial", title: "Glaciar Martial", date: "2027-01-24", month: "Enero", year: 2027, difficulty: "Fácil", location: "Ushuaia, Tierra del Fuego", duration: "Medio día", groupSize: "2-8", price: "$15.000", spotsLeft: 8 },
  { id: "laguna-esmeralda", title: "Laguna Esmeralda", date: "2027-01-25", month: "Enero", year: 2027, difficulty: "Fácil", location: "Ushuaia, Tierra del Fuego", duration: "1 día", groupSize: "2-8", price: "$35.000", spotsLeft: 2 },
  // Febrero 2027
  { id: "laguna-esmeralda", title: "Laguna Esmeralda", date: "2027-02-07", month: "Febrero", year: 2027, difficulty: "Fácil", location: "Ushuaia, Tierra del Fuego", duration: "1 día", groupSize: "2-8", price: "$35.000", spotsLeft: 8 },
  { id: "glaciar-martial", title: "Glaciar Martial", date: "2027-02-08", month: "Febrero", year: 2027, difficulty: "Fácil", location: "Ushuaia, Tierra del Fuego", duration: "Medio día", groupSize: "2-8", price: "$15.000", spotsLeft: 6 },
  { id: "ojo-del-albino", title: "Glaciar Ojo del Albino", date: "2027-02-14", month: "Febrero", year: 2027, difficulty: "Moderado", location: "Ushuaia, Tierra del Fuego", duration: "1 día", groupSize: "2-6", price: "$45.000", spotsLeft: 4 },
  { id: "vinciguerra", title: "Glaciar Vinciguerra y Laguna Azul", date: "2027-02-15", month: "Febrero", year: 2027, difficulty: "Avanzado", location: "Ushuaia, Tierra del Fuego", duration: "1 día", groupSize: "2-6", price: "$65.000", spotsLeft: 3 },
  { id: "laguna-esmeralda", title: "Laguna Esmeralda", date: "2027-02-21", month: "Febrero", year: 2027, difficulty: "Fácil", location: "Ushuaia, Tierra del Fuego", duration: "1 día", groupSize: "2-8", price: "$35.000", spotsLeft: 7 },
  { id: "campamento-vinciguerra", title: "Campamento Vinciguerra", date: "2027-02-22", month: "Febrero", year: 2027, difficulty: "Avanzado", location: "Ushuaia, Tierra del Fuego", duration: "2 días", groupSize: "2-6", price: "$130.000", spotsLeft: 2 },
]

// ─── In-memory bookings store ────────────────────────────────────────────────

export const bookings: Array<{
  id: string
  activityId: string
  activityTitle: string
  date: string
  firstName: string
  lastName: string
  email: string
  phone: string
  pickupAddress: string
  city: string
  references: string
  isHotel: boolean
  hotelName: string
  guests: number
  total: number
  currency: string
  status: "confirmed" | "pending"
  createdAt: string
}> = []

// ─── In-memory contact messages store ────────────────────────────────────────

export const contactMessages: Array<{
  id: string
  name: string
  email: string
  phone: string
  subject: string
  message: string
  createdAt: string
}> = []
